### ISSUE TITLE
how to to store data with admin panel

### ISSUE THREAD

**Issue by aslamsk** [AdityaKumawat97/react-e-commerce-website#9]
how to to store data with admin panel

**Comment by AdityaKumawat97** [comment]
The idea is simple: 
I am actually slammed with work, but I will shift all types of data onto firestore, and create an admin access
Then create a seperate page for admin panel (preferably some ready made ones like SB admin panel) access the data from firestore

**Comment by AdityaKumawat97** [comment]
Closing it as it has no response also I need to completely migrate all data to firestore to perform the particular operation.
